### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by wangdemon** [JC3/ModelSplit#15]
I don't know whether it is the problem of the program or the problem of the model. No 3D model has been successfully segmented
Look at the picture below:
![1](https://user-images.githubusercontent.com/20681339/197471297-a6d55feb-0201-46fa-bd54-b0b919963cae.png)
![2](https://user-images.githubusercontent.com/20681339/197471311-cdc3218d-6c38-416a-9833-9cc378d2a04a.png)

**Comment by JC3** [comment]
I haven't looked at this code in a while but that looks like it's perhaps having issues with a surface model that has quad faces instead of triangles?

I actually had no idea anybody else was actually using this; maybe I'll clean up the code when I get a chance.

**Comment by wangdemon** [comment]
thank you for your answer.
